from . import property_building
from . import property_dashboard
from . import property_amenity
from . import res_partner_extend
from . import property_unit
from . import property_rental_contract
from . import property_sales_contract
from . import property_maintenance
from . import property_commission
from . import account_move_extend
